# Generated by Django 4.2.18 on 2026-04-18 23:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id_camera', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Cámara')),
                ('modelo', models.CharField(max_length=150)),
                ('ubicacion', models.TextField()),
                ('latitud', models.FloatField(validators=[django.core.validators.MinValueValidator(4.4), django.core.validators.MaxValueValidator(4.9)])),
                ('longitud', models.FloatField(validators=[django.core.validators.MinValueValidator(-74.3), django.core.validators.MaxValueValidator(-73.9)])),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('En Mantenimiento', 'En Mantenimiento')], default='Activa', max_length=20)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('localidad', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Ticket')),
                ('tipo', models.CharField(choices=[('Correctivo', 'Correctivo'), ('Preventivo', 'Preventivo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('En curso', 'En curso'), ('Resuelto', 'Resuelto')], default='Nuevo', max_length=20)),
                ('prioridad', models.CharField(choices=[('Crítica', 'Crítica'), ('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cameras.camera')),
            ],
        ),
    ]
